### ISSUE TITLE
Search fails when you have an apostrophe 

### ISSUE THREAD

**Issue by isse95** [methodgg/wago.io#244]
**When your keyword contains an apostrophe then results  will  always be empty.**
Examples [Fyr'alath](https://wago.io/search/imports/wow/df-weakaura?q=fyr%27alath) 
![chrome_2024-02-26_13-25-25](https://github.com/oratory/wago.io/assets/21156345/ab76ad31-0572-47b1-9400-e66e94b963b3)
vs [Fyralath](https://wago.io/search/imports/wow/df-weakaura?q=fyralath)
![chrome_2024-02-26_13-24-55](https://github.com/oratory/wago.io/assets/21156345/c4ea8757-2bbe-4c24-a72d-58a4bd81d1b4)

**Comment by oratory** [comment]
Fixed a while back, closing

**Comment by isse95** [comment]
> Fixed a while back, closing

Hmm, still broken for me
